insert into lista (nome_lista, eh_favorita, nome_usuario) values ('melhores', true, 'Rosanna');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('piores', false, 'Dominick');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('vencedores', true, 'Meara');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('drama', true, 'Filip');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('comedia', true, 'Roselin');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('para dormir', true, 'Dorree');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('terror', true, 'Rochester');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('melhores2', false, 'Jerad');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('piores2', true, 'Ronalda');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('vencedores2', true, 'Hal');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('drama2', false, 'Francisco');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('comedia2', false, 'Eileen');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('para dormir2', false, 'Brendon');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('terror2', false, 'Evelin');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('melhores3', false, 'Marni');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('piores3', true, 'Didi');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('vencedores3', false, 'Louella');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('drama3', false, 'Robbi');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('comedia3', true, 'Rosana');
insert into lista (nome_lista, eh_favorita, nome_usuario) values ('para dormir3', false, 'Aveline');
