INSERT INTO MIDIA (nome_midia, data_lanc, resumo) VALUES

('Harry Potter e a Pedra Filosofal', '2001-11-23', 'Harry Potter é um garoto órfão que vive infeliz com seus tios, os Dursleys. Ele recebe uma carta contendo um convite para ingressar em Hogwarts, uma famosa escola especializada em formar jovens bruxos. Inicialmente, Harry é impedido de ler a carta por seu tio, mas logo recebe a visita de Hagrid, o guarda-caça de Hogwarts, que chega para levá-lo até a escola. Harry adentra um mundo mágico que jamais imaginara, vivendo diversas aventuras com seus novos amigos, Rony Weasley e Hermione Granger.'), -- FILME
('Harry Potter e a Camara Secreta', '2002-11-22', 'Após as sofríveis férias na casa dos tios, Harry Potter se prepara para voltar a Hogwarts e começar seu segundo ano na escola de bruxos. Na véspera do início das aulas, a estranha criatura Dobby aparece em seu quarto e o avisa de que voltar é um erro e que algo muito ruim pode acontecer se Harry insistir em continuar os estudos de bruxaria. O garoto, no entanto, está disposto a correr o risco e se livrar do lar problemático.'), --
('Harry Potter e o Prisioneiro de Azkaban', '2004-06-04', 'É o início do terceiro ano na escola de bruxaria Hogwarts. Harry, Ron e Hermione têm muito o que aprender. Mas uma ameaça ronda a escola e ela se chama Sirius Black. Após doze anos encarcerado na prisão de Azkaban, ele consegue escapar e volta para vingar seu mestre, Lord Voldemort. Para piorar, os Dementores, guardas supostamente enviados para proteger Hogwarts e seguir os passos de Black, parecem ser ameaças ainda mais perigosas.'), -- FILME
('Harry Potter e o Calice de Fogo', '2005-11-25', 'Harry retorna para seu quarto ano na Escola de Magia e Bruxaria de Hogwarts, junto com os seus amigos Ron e Hermione. Desta vez, acontece um torneio entre as três maiores escola de magia, com um participante selecionado de cada escola, pelo Cálice de Fogo. O nome de Harry aparece, mesmo não tendo se inscrito, e ele precisa competir.'), -- FILME
('O Senhor dos Aneis: O Retorno do Rei', '2003-12-25', 'O confronto final entre as forças do bem e do mal que lutam pelo controle do futuro da Terra Média se aproxima. Sauron planeja um grande ataque a Minas Tirith, capital de Gondor, o que faz com que Gandalf e Pippin partam para o local na intenção de ajudar a resistência. Um exército é reunido por Theoden em Rohan, em mais uma tentativa de deter as forças de Sauron. Enquanto isso, Frodo, Sam e Gollum seguem sua viagem rumo à Montanha da Perdição para destruir o anel.'), -- FILME 
('O Senhor dos Aneis: As Duas Torres', '2002-12-27', 'Após a captura de Merry e Pippy pelos orcs, a Sociedade do Anel é dissolvida. Frodo e Sam seguem sua jornada rumo à Montanha da Perdição para destruir o anel e descobrem que estão sendo perseguidos pelo misterioso Gollum. Enquanto isso, Aragorn, o elfo e arqueiro Legolas e o anão Gimli partem para resgatar os hobbits sequestrados e chegam ao reino de Rohan, onde o rei Theoden foi vítima de uma maldição mortal de Saruman.'), -- FILME 
('O Senhor dos Aneis: A Sociedade do Anel', '2002-01-01', 'Em uma terra fantástica e única, um hobbit recebe de presente de seu tio um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso, o hobbit Frodo tem um caminho árduo pela frente, onde encontra perigo, medo e seres bizarros. Ao seu lado para o cumprimento desta jornada, ele aos poucos pode contar com outros hobbits, um elfo, um anão, dois humanos e um mago, totalizando nove seres que formam a Sociedade do Anel.'), -- FILME 
('O Hobbit: Uma Jornada Inesperada', '2012-12-14', 'Como a maioria dos hobbits, Bilbo Bolseiro leva uma vida tranquila até o dia em que recebe uma missão do mago Gandalf. Acompanhado por um grupo de anões, ele parte numa jornada até a Montanha Solitária para libertar o Reino de Erebor do dragão Smaug.'), -- FILME 
('O Hobbit: A Desolação de Smaug', '2013-12-13', 'Ao lado de um grupo de anões e de Gandalf, Bilbo segue em direção à Montanha Solitária, onde deverá ajudar seus companheiros a retomar a Pedra de Arken. O problema é que o artefato está perdido em meio a um tesouro protegido pelo temido dragão Smaug.'), -- FILME 
('O Hobbit: A Batalha dos Cinco Exercitos', '2014-12-07', 'O dragão Smaug lança sua fúria ardente contra a Cidade do Lago que fica próxima da montanha de Erebor. Bard consegue derrotá-lo, mas, rapidamente, sem a ameaça do dragão, inicia-se uma batalha pelo controle de Erebor e sua riqueza. Os anões, liderados por Thorin, adentram a montanha e estão dispostos a impedir a entrada de elfos, anões e orcs. Bilbo Bolseiro e Gandalf tentam impedir a guerra.'), -- FILME
('Red: Crescer é uma Fera', '2022-02-21', 'Uma menina de 13 anos começa a se transformar em um panda vermelho gigante sempre que fica animada.'), -- FILME
('Encanto', '2021-11-25', 'Encanto da Walt Disney Animation Studios conta a história dos Madrigal, uma família extraordinária que vive escondida nas montanhas da Colômbia, em uma casa mágica, em uma cidade vibrante, em um lugar maravilhoso conhecido como um Encanto. A magia deste Encanto abençoou todos os meninos e meninas da família com um dom único, desde superforça até o poder de curar. Todos, exceto Mirabel. Mas, quando ela descobre que a magia que cerca o Encanto está em perigo, Mirabel decide que ela, a única Madrigal sem poderes mágicos, pode ser a última esperança de sua família excepcional.'), -- FILME
('Sr e Sra Smith', '2005-06-10', 'John e Jane Smith aparentemente parecem formar um casal normal, mas na realidade ambos mantêm um segredo. Os dois são assassinos de aluguel contratados por empresas rivais. A verdade só vem à tona quando John e Jane, sem saber, recebem uma missão para eliminar o mesmo alvo e mais tarde descobrem que devem matar um ao outro.'), -- FILME
('A Lenda do Tesouro Perdido', '2004-12-31', 'O historiador e decodificador Ben Gates tem procurado, durante toda a sua vida, um conhecido tesouro que existe desde a criação dos Estados Unidos. Ao participar de uma expedição liderada pelo caçador de tesouros Ian Howe, Gates encontra um navio colonial preso no gelo do Círculo Ártico que tem uma pista ligando o tesouro com a Declaração da Independência. Mas quando Howe o trai, Gates tem que correr para conseguir o documento antes do seu falso colega.'), -- FILME
('O Rei do Show', '2017-12-28', 'P. T. Barnum, um showman que tem uma tendência natural de enganar seu público, decide montar um circo na esperança de ficar famoso. Durante sua saga há ainda uma importante questão pendente em sua vida, uma paixão cega pela cantora Jenny Lind.'), -- FILME
('Homem-Aranha: De Volta ao Lar', '2017-07-06', 'Depois de lutar ao lado dos Vingadores, chegou a hora do jovem Peter Parker voltar para casa em Nova York ao lado de sua tia May. Sob o olhar atento do mentor Tony Stark, Peter começa a abraçar sua nova identidade como Homem-Aranha e combate diariamente pequenos crimes nas redondezas. Ele acredita que encontrou a missão de sua vida quando o terrível vilão Abutre surge ameaçando a cidade. O problema é que a tarefa não será tão fácil como ele imaginava.'), -- FILME
('Homem-Aranha: Longe de Casa', '2019-07-04', 'Peter Parker está em uma viagem de duas semanas pela Europa, ao lado de seus amigos de colégio, quando é surpreendido pela visita de Nick Fury. Convocado para mais uma missão heroica, ele precisa enfrentar vários vilões que surgem em cidades-símbolo do continente, como Londres, Paris e Veneza, e também a aparição do enigmático Mysterio.'), -- FILME
('Extraordinario', '2017-12-07', 'Auggie Pullman é um garoto que nasceu com uma deformidade facial e precisou passar por 27 cirurgias plásticas. Aos 10 anos, ele finalmente começa a frequentar uma escola regular, como qualquer outra criança, pela primeira vez. No quinto ano, ele precisa se esforçar para conseguir se encaixar em sua nova realidade.'), -- FILME
('Duro de Matar: A Vingança', '1995-09-29', 'O policial John McClane está divorciado, vive bêbado e foi despedido do trabalho pelo seu comportamento negligente e péssima atitude. Chamado de volta à ação, enfrenta um terrorista que usa Nova York como refém. Em um jogo mortal, o terrorista se recusa a falar com qualquer outro que não seja McClane. O detetive se une ao eletricista de rua Zeus Carver na tentativa de se aproximar do terrorista.'), -- FILME
('A Procura da Felicidade', '2007-02-02', 'Chris enfrenta sérios problemas financeiros e Linda, sua esposa, decide partir. Ele agora é pai solteiro e precisa cuidar de Christopher, seu filho de 5 anos. Chris tenta usar sua habilidade como vendedor para conseguir um emprego melhor, mas só consegue um estágio não remunerado. Seus problemas financeiros não podem esperar uma promoção e eles acabam despejados. Chris e Christopher passam a dormir em abrigos ou onde quer que consigam um refúgio, mantendo a esperança de que dias melhores virão.'), -- FILME

('Don Juan', '2007-12-27', 'Batizada de Don Juan ou O convidado de pedra, a peça de Molière é uma comédia de cinco atos que se passa na Sicília. O protagonista é um nobre irresponsável que passa seu tempo conquistando mulheres (para descartá-las em seguida), dizendo blasfêmias, contando mentiras e, resumindo, arranjando confusão.'), -- LIVRO
('Memorial do Convento', '2020-11-02', '"Memorial do Convento" é um romance que critica a história, a sociedade e a hipocrisia religiosa. Em uma mistura de personagens reais e fictícios, José Saramago aborda temáticas como o amor, as relações humanas, a religião e a exploração do povo pobre em prol dos desejos dos governantes .'), -- LIVRO
('O inominável', '2020-02-13', 'O romance pode ser resumido como um longo monólogo de uma voz anônima, além do tempo e espaço. Uma voz que parece, por vezes, representar os pensamentos do autor mas que, por outro lado, não se define nunca como quem ou quê, um sujeito sempre indefinido.'), -- LIVRO
('Mulheres que correm com os lobos', '2018-09-17', 'Sensações de vazio, fadiga, medo, depressão, fragilidade, bloqueio e falta de criatividade são sintomas cada vez mais freqüentes entre as mulheres modernas, assoberbadas com o acúmulo de funções na família e na vida profissional.'), -- LIVRO
('Vermelho, branco e sangue azul', '2019-11-04', 'A história foca na vida de Alex e Henry, dois homens entrando na vida adulta, mas já com o peso de muitas responsabilidades nas costas: um é filho da primeira presidente mulher dos Estados Unidos e o outro é um príncipe, herdeiro da coroa britânica.'), -- LIVRO
('A revolução dos bichos', '2007-01-10', 'A Revolução dos Bichos, de George Orwell, se passa numa granja liderada, inicialmente, pelo Sr. Jones. Porém, insatisfeitos com a dominação e exploração e liderados pelo Porco Major, os animais decidem fazer uma revolução. Assim, o inimigo seria aquele que anda sobre duas pernas.'), -- LIVRO
('1984', '2009-07-21', 'Após uma guerra global, semelhante à segunda grande guerra, porém com mais bombas atômicas, o mundo foi dividido em três continentes: Lestásia, Eurásia e Oceania, onde fica a cidade de Londres. Esse último é comandado pelo líder Big Brother, a figura máxima de poder e controle, "o olho que tudo vê".'), -- LIVRO
('Como Eu Era Antes de Você', '2013-04-09', 'Aos 26 anos, Louisa Clark não tem muitas ambições. Ela mora com os pais, a irmã mãe solteira, o sobrinho pequeno e um avô que precisa de cuidados constantes desde que sofreu um derrame. Além disso, trabalha como garçonete num café, um emprego que ela adora e que, apesar de não pagar muito, ajuda nas despesas. E namora Patrick, um triatleta que não parece interessado nela. Não que ela se importe.'), -- LIVRO
('Orgulho e Preconceito', '2018-04-12', 'O enredo de Orgulho e preconceito gira em torno da família Bennet, composta por marido, mulher e cinco filhas (Jane, Elizabeth, Mary, Kitty e Lydia). A história se passa em uma zona rural da Inglaterra durante o início do século XIX. Elizabeth Bennet, a segunda filha mais velha, será a protagonista da trama. Uma jovem bela, orgulhosa, de personalidade forte e vanguardista para o seu tempo, Lizzie, como é chamada pelos íntimos, carrega dentro de si inquietações com as convenções sociais do seu tempo.'), -- LIVRO
('O Pequeno Príncipe', '2018-08-27', 'O Pequeno Príncipe conta a história mágica, sensível, comovente, do encontro de um uma frágil criança loura, que diz ter vindo de um pequeno planeta distante, e um piloto que caiu com seu avião em um deserto.'), -- LIVRO
('O Pequeno Príncipe', '2015-01-09', 'O Pequeno Príncipe conta a história mágica, sensível, comovente, do encontro de um uma frágil criança loura, que diz ter vindo de um pequeno planeta distante, e um piloto que caiu com seu avião em um deserto.'), -- LIVRO
('Um Estudo em Vermelho', '2013-08-01', 'Um estudo em vermelho propõe um enigma terrível e invencível para a polícia, que pede auxílio a Holmes: um homem é encontrado morto, sem ferimentos e cercado de manchas de sangue. Em seu rosto uma expressão de pavor. Um caso para Sherlock Holmes e suas fascinantes deduções narrado por seu amigo Dr.'), -- LIVRO
('O Retrato de Dorian Gray', '2021-10-15', 'Neste livro, o belo jovem Dorian Gray, o protagonista, torna-se modelo para uma pintura do artista Basil Hallward. O pintor apresenta Dorian ao Lorde Henry Wotton, que o faz tomar consciência de sua beleza e do valor de sua juventude e o inicia num mundo de vícios e desregramento.'), -- LIVRO
('O Colecionador', '2018-04-12', 'O COLECIONADOR é a história de Frederick Clegg, um homem solitário, de origem humilde, menosprezado por uma sociedade esnobe, que encontra o grande amor de sua vida. Tudo o que ele deseja é passar um tempo a sós com ela, demonstrar seus nobres sentimentos e deixar claro que eles nasceram um para o outro.'), -- LIVRO
('A Seleção', '2012-09-17', 'É a oportunidade de ser alçada a um mundo de vestidos deslumbrantes e joias valiosas. De morar em um palácio, conquistar o coração do belo príncipe Maxon e um dia ser a rainha. America Singer, no entanto, estar entre as Selecionadas é um pesadelo. Significa deixar para trás o rapaz que ama.'), -- LIVRO
('Corte de Espinhos e Rosas', '2015-10-09', 'O livro Corte de Espinhos e Rosas conta a história de Feyre, uma humana que vive na extrema pobreza e tem que se virar sozinha para sustentar suas duas irmãs e seu pai. O mundo em que ela vive é dividido entre humanos e seres mágicos chamados feéricos, considerados assassinos cruéis da raça humana.'), -- LIVRO
('O Morro dos Ventos Uivantes', '2020-07-14', 'O livro retrata uma trágica historia de amor e obsessão em que os personagens principais são a obstinada e geniosa Catherine Earnshaw e seu irmão adotivo, Heathcliff.'), -- LIVRO
('Messias de Duna', '2017-07-05', 'O Messias de Duna, escrito por Frank Herbert, é o segundo romance da série de ficção científica. Ela revela um lado mais humano de seus personagens, além de aprofundar e estender o universo de Duna, aliando discussões políticas, filosóficas e religiosas à épica história de poder, vingança e redenção.'), -- LIVRO
('Filhos de Duna', '2017-08-31', 'O Imperium vive um interregno após Paul Atreides abdicar de seu título de imperador e entregar-se ao deserto. Sua irmã, Alia, ascende ao poder como regente enquanto os filhos de Muad Dib não são capazes de assumir o Trono do Leão.'), -- LIVRO
('O Homem de Giz', '2018-03-15', 'Em 2016, Eddie se esforça para superar o passado, até que um dia ele e os amigos de infância recebem um mesmo aviso: o desenho de um homem de giz enforcado. Quando um dos amigos aparece morto, Eddie tem certeza de que precisa descobrir o que de fato aconteceu trinta anos atrás.'), -- LIVRO
('O que aconteceu com Annie', '2019-05-15', 'Um homem fracassado e atormentado pelos fantasmas do passado. Atolado em dívidas e correndo sérios riscos de morte, recebe um convite misterioso para voltar às suas origens e descobrir o que aconteceu com sua irmã, Annie, que há 25 anos sumiu e quando voltou nunca mais foi a mesma.'), -- LIVRO
('Outras pessoas', '2020-06-16', 'Gabe Forman está preso em um engarrafamento, atrasado para o jantar em casa com a família, quando o rosto de sua filha, Izzy, de cinco anos, aparece no vidro traseiro do carro à frente e balbucia “papai”. Três anos depois, Gabe passa seus dias e noites rodando pela estrada em que viu Izzy pela última vez.'), -- LIVRO
('A Garota do Lago', '2017-01-01', 'Filha de um poderoso advogado, Becca estava no auge de sua vida. Atraída Instintivamente pela notícia, a repórter Kelsey Castle vai até a cidade para investigar o caso. ... E Logo Se Estabelece Uma Conexão Íntima Quando Um Vivo Caminha Nas Mesmas Pegadas Dos Mortos...'), -- LIVRO
('A Parte Que Falta', '2018-02-09', 'O protagonista desta história é um ser circular que visivelmente não está completo: falta-lhe uma parte. E ele acredita que existe pelo mundo uma forma que vai completá-lo perfeitamente e que, quando estiver completo, vai se sentir feliz de vez. Então ele parte animado em uma jornada em busca de sua parte que falta.'), -- LIVRO

('Breaking Bad', '2008-01-20', 'O novo drama "Breaking Bad" narra a história de Walter White (Bryan Cranston), um humilde professor de química que vê sua vida se transformar quando descobre ser portador de um câncer terminal.'), -- SERIE
('Avatar: A Lenda de Aang', '2005-02-21', 'Aang é um menino de apenas 12 anos que descobre ser o Avatar, grande mestre responsável por garantir o equilíbrio entre os quatro elementos - água, terra, fogo e ar - e suas respectivas nações representantes, mantendo o planeta em segurança.'), -- SERIE
('Rick e Morty', '2013-12-02', 'O show gira em torno das aventuras dos membros da família Smith, que consiste nos pais Jerry e Beth, seus filhos Summer e Morty, e o pai de Beth, chamado Rick Sanchez, que mora com eles como hóspede. De acordo com Justin Roiland, a família mora fora da cidade de Seattle, no estado norte-americano de Washington.'), -- SERIE
('Arcane', '2021-11-06', 'Baseada no universo de League of Legends (LOL), o famoso jogo da Riot Games, Arcane é uma série de animação que gira em torno do equilíbrio entre a riqueza de Piltover e a decadência de Zaun.'), -- SERIE
('O Gambito da Rainha', '2020-10-23', 'O Gambito da Rainha conta a história de Beth Harmon (Anya Taylor-Joy), uma menina órfã que se revela um prodígio do xadrez. Mas agora, aos 22 anos, ela precisa enfrentar seu vício para conseguir se tornar a maior jogadora do mundo.'), -- SERIE
('Fargo', '2014-04-15', 'Fargo é um misto de drama com comédia de humor negro. A trama mostra uma sequência de crimes que saem errado e são investigados pela detetive Molly Solverson . Como personagens principais temos Lester e Malvo. O primeiro é um pacato vendedor de seguros que sofre bullyng do irmão, esposa e ex colegas de trabalho.'), -- SERIE
('Black Mirror', '2011-12-04', 'Black Mirror é uma série de televisão britânica antológica de ficção científica criada por Charlie Brooker e centrada em temas obscuros e satíricos que examinam a sociedade moderna, particularmente a respeito das consequências imprevistas das novas tecnologias.'), -- SERIE
('Dark', '2017-12-01', 'Uma criança desaparecida leva quatro famílias a uma busca frenética por respostas, que revela um incrível mistério envolvendo três gerações.'), -- SERIE
('Stranger Things', '2016-07-15', 'Em 6 de Novembro, 1983 na pequena cidade de Hawkins, Indiana, o garoto de 12 anos, Will Byers desaparece misteriosamente. A mãe de Will, Joyce, torna-se frenética e tenta encontrar Will enquanto o chefe de polícia Jim Hopper começa a investigar, e assim fazem também os amigos de Will: Dustin, Mike e Lucas.'), -- SERIE
('BoJack Horseman', '2014-08-22', 'BoJack (Will Arnett) é um decadente cavalo que trabalha na TV. Uma estrela já esquecida de um seriado da década de 1990 chamado Horsin Around, ele disfarça sua baixa auto-estima com uísque e relações fracassadas.'), -- SERIE
('Anne With an "E"', '2017-03-19', 'Anne with an E é uma série canadense transmitida originalmente pelo canal CBC Television. A história acompanha a vida de Anne Shirley, uma jovem órfã que, após uma infância de abusos entre orfanatos e casas de estranhos, é enviada por engano para viver com um casal de irmãos em idade avançada.'), -- SERIE
('The Crown', '2016-11-04', 'Em The Crown, a filha do rei George VI (Jared Harris), Elizabeth II (Claire Foy) sempre soube que não teria uma vida comum. Após a morte do seu pai em 1952, ela dá seus primeiros passos em direção ao trono inglês, a começar pelas audiências semanais com os primeiro-ministros.'), -- SERIE
('A Maldição da Residência Hill', '2018-10-12', 'A família Crain se muda para a Residência Hill com o objetivo de reformá-la e, após alguns poucos meses, revendê-la ganhando um bom lucro em cima.'), -- SERIE
('Vikings', '2013-03-03', 'Vikings segue a vida de Ragnar Lothbrok (Travis Fimmel), o maior guerreiro da sua era. Lider de seu bando, com seus irmãos e sua família, ele ascende ao poder e torna-se Rei da tribo dos vikings. Além de guerreiro implacável, Ragnar segue as tradições nórdicas e é devoto dos deuses.'), -- SERIE
('Suits', '2011-06-23', 'Mike Ross (Patrick J. Adams) é um garoto que abandonou a faculdade de direito mas, brilhante como é, consegue uma entrevista com o respeitado Harvey Specter (Gabriel Macht), um dos melhores advogados de Manhattan.'), -- SERIE
('Outlander', '2014-08-09', 'Outlander conta a história de Claire Randall (Caitriona Balfe), uma enfermeira em combate no ano de 1945. Ela é misteriosamente transportada através do tempo e mandada para 1743, e sua vida passa a correr riscos que ela desconhece. Forçada a se casar com Jamie Fraser (Sam Heughan), um cortês e nobre guerreiro escocês.'), -- SERIE
('Brooklyn Nine-Nine', '2013-09-17', 'A série Brooklyn Nine-Nine é ambientada na 99ª Delegacia de Polícia de Nova York, no Brooklyn, acompanhando as maluquices do imaturo detetive Jake Peralta (Andy Samberg) e a relação que ele tem com o novo capitão, Ray Holt (Andre Braugher).'), -- SERIE
('The Witcher', '2019-12-20', 'The Witcher se passa em um mundo de fantasia medieval e segue a história de Geralt de Rívia (Henry Cavill), um dos últimos bruxos restantes na Terra. Ele busca encontrar seu lugar em um mundo onde as pessoas muitas vezes são mais perversas que as criaturas selvagens.'), -- SERIE
('La casa de papel', '2017-05-02', 'Oito ladrões se trancam com reféns na Casa da Moeda da Espanha. Seu líder manipula a polícia para realizar um plano. Será o maior roubo da história, ou uma missão em vão?'); -- SERIE

