INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (1,'Bogey Awards', 'Bogey Award in Titanium', '2001-01-01');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (1,'Broadcast Film Critcis Association Award', 'Best Family Film', '2002-01-11');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (1,'Broadcast Music Incorporated Film & TV', 'BMI Fil Music Award', '2002-05-15');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (1,'Casting Society of America', 'Feature Film Casting – Comedy', '2002-08-17');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (1,'Costume Designers Guild Award', 'Excellence in Fantasy Film', '2002-03-16');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (1,'Evening Standard British Film Awards', 'Evening Standard British Film Awards', '2002-03-02');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (7,'Academy Awards', 'Best Cinematography', '2001-03-01');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (7,'Academy Awards', 'Best Film Editing', '2002-09-12');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (7,'Academy Awards', 'Best Original Score', '2002-08-29');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (7,'Academy Awards', 'Best Visual Effects', '2002-02-26');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (7,'Saturn Awards', 'Best Fantasy Film', '2002-03-15');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (7,'Saturn Awards', 'Best Director', '2002-11-06');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (7,'Saturn Awards', 'Best Supporting Actor', '2002-04-14');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (8,'ASCAP Awards', 'Top Box Office Films', '2013-03-28');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (8,'Academy Awards', 'Scientific and Engineering Award', '2013-01-05');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (8,'AEAF Awards 2013', 'Feature Film - Visual Effects', '2014-09-13');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (8,'Australia Box Office Awards', 'Real D Award for Highest Grossing 3D Film in Australia', '2013-07-12');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (8,'Australia Box Office Awards', 'Real D Award for Highest Grossing Film in New Zealand', '2013-07-13');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (8,'Empire Awards', 'Best Sci-Fi/Fantasy', '2014-05-06');
INSERT INTO premiacao (id_midia, nome_prem, categoria, data_prem) values (8,'Houston Film Critics Society', 'Technical Achievement', '2013-12-15');
